# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: Reach Zhai
google_analytics: dbyll
title: Reach Zhai

defaults:
  -
    scope:
      path: "http://reachzhai.github.io/"
    values:
      title: Reach Zhai

description: Android developer
author:
  name: Reach Zhai
  email: zl280513013@sina.com
  github: reachzhai
  twitter: reachzhai
  pinterest: asd123
  linkedin: reachzhai
  bio: i like here!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate